# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  postgres:
    container_name: database-postgres
    ports:
    - 5433:5432
    environment:
    - POSTGRES_PASSWORD=Unu#2023
  serilogseq:
    container_name: serilogseq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80